name: NoBuildPlus
main: p1xel.nobuildplus.NoBuildPlus
version: 1.5.51
api-version: 1.13
softdepend: [Residence, Dominion, BlockRegen]
folia-supported: true
commands:
  nobuildplus:
    aliases: [nbp]
permissions:
  nobuildplus.use:
    default: op
    description: Using the commands
  nobuildplus.gui:
    default: op
    description: Using GUI management