name: NoBuildPlus
main: p1xel.nobuildplus.NoBuildPlus
version: 1.5.4
api-version: 1.13
commands:
  nobuildplus:
    aliases: [nbp]
permissions:
  nobuildplus.use:
    default: op
    description: Using the commands
  nobuildplus.gui:
    default: op
    description: Using GUI management